from .from_theme import from_theme
from .types import Config
from .validators import (
    is_any,
    is_arbitrary_image,
    is_arbitrary_length,
    is_arbitrary_number,
    is_arbitrary_position,
    is_arbitrary_shadow,
    is_arbitrary_size,
    is_arbitrary_value,
    is_integer,
    is_length,
    is_number,
    is_percent,
    is_tshirt_size,
)

def get_default_config() -> Config:
    # Theme getters
    colors = from_theme('colors')
    spacing = from_theme('spacing')
    blur = from_theme('blur')
    brightness = from_theme('brightness')
    border_color = from_theme('borderColor')
    border_radius = from_theme('borderRadius')
    border_spacing = from_theme('borderSpacing')
    border_width = from_theme('borderWidth')
    contrast = from_theme('contrast')
    grayscale = from_theme('grayscale')
    hue_rotate = from_theme('hueRotate')
    invert = from_theme('invert')
    gap = from_theme('gap')
    gradient_color_stops = from_theme('gradientColorStops')
    gradient_color_stop_positions = from_theme('gradientColorStopPositions')
    inset = from_theme('inset')
    margin = from_theme('margin')
    opacity = from_theme('opacity')
    padding = from_theme('padding')
    saturate = from_theme('saturate')
    scale = from_theme('scale')
    sepia = from_theme('sepia')
    skew = from_theme('skew')
    space = from_theme('space')
    translate = from_theme('translate')

    def get_overscroll():
        return ['auto', 'contain', 'none']

    def get_overflow():
        return ['auto', 'hidden', 'clip', 'visible', 'scroll']

    def get_spacing_with_auto_and_arbitrary():
        return ['auto', is_arbitrary_value, spacing]

    def get_spacing_with_arbitrary():
        return [is_arbitrary_value, spacing]

    def get_length_with_empty_and_arbitrary():
        return ['', is_length, is_arbitrary_length]

    def get_number_with_auto_and_arbitrary():
        return ['auto', is_number, is_arbitrary_value]
    
    def get_positions():
        return [
            'bottom',
            'center',
            'left',
            'left-bottom',
            'left-top',
            'right',
            'right-bottom',
            'right-top',
            'top',
        ]

    def get_line_styles():
        return ['solid', 'dashed', 'dotted', 'double', 'none']

    def get_blend_modes():
        return [
            'normal',
            'multiply',
            'screen',
            'overlay',
            'darken',
            'lighten',
            'color-dodge',
            'color-burn',
            'hard-light',
            'soft-light',
            'difference',
            'exclusion',
            'hue',
            'saturation',
            'color',
            'luminosity',
        ]

    def get_align():
        return ['start', 'end', 'center', 'between', 'around', 'evenly', 'stretch']

    def get_zero_and_empty():
        return ['', '0', is_arbitrary_value]

    def get_breaks():
        return ['auto', 'avoid', 'all', 'avoid-page', 'page', 'left', 'right', 'column']

    def get_number_and_arbitrary():
        return [is_number, is_arbitrary_value]

    return {
        'cache_size': 500,
        'separator': ':',
        'theme': {
            'colors': [is_any],
            'spacing': [is_length, is_arbitrary_length],
            'blur': ['none', '', is_tshirt_size, is_arbitrary_value],
            'brightness': get_number_and_arbitrary(),
            'borderColor': [colors],
            'borderRadius': ['none', '', 'full', is_tshirt_size, is_arbitrary_value],
            'borderSpacing': get_spacing_with_arbitrary(),
            'borderWidth': get_length_with_empty_and_arbitrary(),
            'contrast': get_number_and_arbitrary(),
            'grayscale': get_zero_and_empty(),
            'hueRotate': get_number_and_arbitrary(),
            'invert': get_zero_and_empty(),
            'gap': get_spacing_with_arbitrary(),
            'gradientColorStops': [colors],
            'gradientColorStopPositions': [is_percent, is_arbitrary_length],
            'inset': get_spacing_with_auto_and_arbitrary(),
            'margin': get_spacing_with_auto_and_arbitrary(),
            'opacity': get_number_and_arbitrary(),
            'padding': get_spacing_with_arbitrary(),
            'saturate': get_number_and_arbitrary(),
            'scale': get_number_and_arbitrary(),
            'sepia': get_zero_and_empty(),
            'skew': get_number_and_arbitrary(),
            'space': get_spacing_with_arbitrary(),
            'translate': get_spacing_with_arbitrary(),
        },
        'class_groups': {
            # Layout
            'aspect': [{'aspect': ['auto', 'square', 'video', is_arbitrary_value]}],
            'container': ['container'],
            'columns': [{'columns': [is_tshirt_size]}],
            'break-after': [{'break-after': get_breaks()}],
            'break-before': [{'break-before': get_breaks()}],
            'break-inside': [{'break-inside': ['auto', 'avoid', 'avoid-page', 'avoid-column']}],
            'box-decoration': [{'box-decoration': ['slice', 'clone']}],
            'box': [{'box': ['border', 'content']}],
            'display': [
                'block',
                'inline-block',
                'inline',
                'flex',
                'inline-flex',
                'table',
                'inline-table',
                'table-caption',
                'table-cell',
                'table-column',
                'table-column-group',
                'table-footer-group',
                'table-header-group',
                'table-row-group',
                'table-row',
                'flow-root',
                'grid',
                'inline-grid',
                'contents',
                'list-item',
                'hidden',
            ],
            'float': [{'float': ['right', 'left', 'none', 'start', 'end']}],
            'clear': [{'clear': ['left', 'right', 'both', 'none', 'start', 'end']}],
            'isolation': ['isolate', 'isolation-auto'],
            'object-fit': [{'object': ['contain', 'cover', 'fill', 'none', 'scale-down']}],
            'object-position': [{'object': [*get_positions(), is_arbitrary_value]}],
            'overflow': [{'overflow': get_overflow()}],
            'overflow-x': [{'overflow-x': get_overflow()}],
            'overflow-y': [{'overflow-y': get_overflow()}],
            'overscroll': [{'overscroll': get_overscroll()}],
            'overscroll-x': [{'overscroll-x': get_overscroll()}],
            'overscroll-y': [{'overscroll-y': get_overscroll()}],
            'position': ['static', 'fixed', 'absolute', 'relative', 'sticky'],
            'inset': [{'inset': [inset]}],
            'inset-x': [{'inset-x': [inset]}],
            'inset-y': [{'inset-y': [inset]}],
            'start': [{'start': [inset]}],
            'end': [{'end': [inset]}],
            'top': [{'top': [inset]}],
            'right': [{'right': [inset]}],
            'bottom': [{'bottom': [inset]}],
            'left': [{'left': [inset]}],
            'visibility': ['visible', 'invisible', 'collapse'],
            'z': [{'z': ['auto', is_integer, is_arbitrary_value]}],

            # Flexbox and Grid
            'basis': [{'basis': get_spacing_with_auto_and_arbitrary()}],
            'flex-direction': [{'flex': ['row', 'row-reverse', 'col', 'col-reverse']}],
            'flex-wrap': [{'flex': ['wrap', 'wrap-reverse', 'nowrap']}],
            'flex': [{'flex': ['1', 'auto', 'initial', 'none', is_arbitrary_value]}],
            'grow': [{'grow': get_zero_and_empty()}],
            'shrink': [{'shrink': get_zero_and_empty()}],
            'order': [{'order': ['first', 'last', 'none', is_integer, is_arbitrary_value]}],
            'grid-cols': [{'grid-cols': [is_any]}],
            'col-start-end': [{
                'col': [
                    'auto',
                    {'span': ['full', is_integer, is_arbitrary_value]},
                    is_arbitrary_value,
                ],
            }],
            'col-start': [{'col-start': get_number_with_auto_and_arbitrary()}],
            'col-end': [{'col-end': get_number_with_auto_and_arbitrary()}],
            'grid-rows': [{'grid-rows': [is_any]}],
            'row-start-end': [{'row': ['auto', {'span': [is_integer, is_arbitrary_value]}, is_arbitrary_value]}],
            'row-start': [{'row-start': get_number_with_auto_and_arbitrary()}],
            'row-end': [{'row-end': get_number_with_auto_and_arbitrary()}],
            'grid-flow': [{'grid-flow': ['row', 'col', 'dense', 'row-dense', 'col-dense']}],
            'auto-cols': [{'auto-cols': ['auto', 'min', 'max', 'fr', is_arbitrary_value]}],
            'auto-rows': [{'auto-rows': ['auto', 'min', 'max', 'fr', is_arbitrary_value]}],
            'gap': [{'gap': [gap]}],
            'gap-x': [{'gap-x': [gap]}],
            'gap-y': [{'gap-y': [gap]}],
            'justify-content': [{'justify': ['normal', *get_align()]}],
            'justify-items': [{'justify-items': ['start', 'end', 'center', 'stretch']}],
            'justify-self': [{'justify-self': ['auto', 'start', 'end', 'center', 'stretch']}],
            'align-content': [{'content': ['normal', *get_align(), 'baseline']}],
            'align-items': [{'items': ['start', 'end', 'center', 'baseline', 'stretch']}],
            'align-self': [{'self': ['auto', 'start', 'end', 'center', 'stretch', 'baseline']}],
            'place-content': [{'place-content': [*get_align(), 'baseline']}],
            'place-items': [{'place-items': ['start', 'end', 'center', 'baseline', 'stretch']}],
            'place-self': [{'place-self': ['auto', 'start', 'end', 'center', 'stretch']}],

            # Spacing
            'p': [{'p': [padding]}],
            'px': [{'px': [padding]}],
            'py': [{'py': [padding]}],
            'ps': [{'ps': [padding]}],
            'pe': [{'pe': [padding]}],
            'pt': [{'pt': [padding]}],
            'pr': [{'pr': [padding]}],
            'pb': [{'pb': [padding]}],
            'pl': [{'pl': [padding]}],
            'm': [{'m': [margin]}],
            'mx': [{'mx': [margin]}],
            'my': [{'my': [margin]}],
            'ms': [{'ms': [margin]}],
            'me': [{'me': [margin]}],
            'mt': [{'mt': [margin]}],
            'mr': [{'mr': [margin]}],
            'mb': [{'mb': [margin]}],
            'ml': [{'ml': [margin]}],
            'space-x': [{'space-x': [space]}],
            'space-x-reverse': ['space-x-reverse'],
            'space-y': [{'space-y': [space]}],
            'space-y-reverse': ['space-y-reverse'],

            # Sizing
            'w': [{
                'w': [
                    'auto',
                    'min',
                    'max',
                    'fit',
                    'svw',
                    'lvw',
                    'dvw',
                    is_arbitrary_value,
                    spacing,
                ],
            }],
            'min-w': [{'min-w': [is_arbitrary_value, spacing, 'min', 'max', 'fit']}],
            'max-w': [{
                'max-w': [
                    is_arbitrary_value,
                    spacing,
                    'none',
                    'full',
                    'min',
                    'max',
                    'fit',
                    'prose',
                    {'screen': [is_tshirt_size]},
                    is_tshirt_size,
                ],
            }],
            'h': [{
                'h': [
                    is_arbitrary_value,
                    spacing,
                    'auto',
                    'min',
                    'max',
                    'fit',
                    'svh',
                    'lvh',
                    'dvh',
                ],
            }],
            'min-h': [{
                'min-h': [
                    is_arbitrary_value,
                    spacing,
                    'min',
                    'max',
                    'fit',
                    'svh',
                    'lvh',
                    'dvh'
                ],
            }],
            'max-h': [{
                'max-h': [
                    is_arbitrary_value,
                    spacing,
                    'min',
                    'max',
                    'fit',
                    'svh',
                    'lvh',
                    'dvh'
                ],
            }],
            'size': [{'size': [is_arbitrary_value, spacing, 'auto', 'min', 'max', 'fit']}],

            # Typography
            'font-size': [{'text': ['base', is_tshirt_size, is_arbitrary_length]}],
            'font-smoothing': ['antialiased', 'subpixel-antialiased'],
            'font-style': ['italic', 'not-italic'],
            'font-weight': [{
                'font': [
                    'thin',
                    'extralight',
                    'light',
                    'normal',
                    'medium',
                    'semibold',
                    'bold',
                    'extrabold',
                    'black',
                    is_arbitrary_number,
                ],
            }],
            'font-family': [{'font': [is_any]}],
            'fvn-normal': ['normal-nums'],
            'fvn-ordinal': ['ordinal'],
            'fvn-slashed-zero': ['slashed-zero'],
            'fvn-figure': ['lining-nums', 'oldstyle-nums'],
            'fvn-spacing': ['proportional-nums', 'tabular-nums'],
            'fvn-fraction': ['diagonal-fractions', 'stacked-fractons'],
            'tracking': [{
                'tracking': [
                    'tighter',
                    'tight',
                    'normal',
                    'wide',
                    'wider',
                    'widest',
                    is_arbitrary_value,
                ],
            }],
            'line-clamp': [{'line-clamp': ['none', is_number, is_arbitrary_number]}],
            'leading': [{
                'leading': [
                    'none',
                    'tight',
                    'snug',
                    'normal',
                    'relaxed',
                    'loose',
                    is_length,
                    is_arbitrary_value,
                ],
            }],
            'list-image': [{'list-image': ['none', is_arbitrary_value]}],
            'list-style-type': [{'list': ['none', 'disc', 'decimal', is_arbitrary_value]}],
            'list-style-position': [{'list': ['inside', 'outside']}],
            'placeholder-color': [{'placeholder': [colors]}],
            'placeholder-opacity': [{'placeholder-opacity': [opacity]}],
            'text-alignment': [{'text': ['left', 'center', 'right', 'justify', 'start', 'end']}],
            'text-color': [{'text': [colors]}],
            'text-opacity': [{'text-opacity': [opacity]}],
            'text-decoration': ['underline', 'overline', 'line-through', 'no-underline'],
            'text-decoration-style': [{'decoration': [*get_line_styles(), 'wavy']}],
            'text-decoration-thickness': [{'decoration': ['auto', 'from-font', is_length, is_arbitrary_length]}],
            'underline-offset': [{'underline-offset': ['auto', is_length, is_arbitrary_value]}],
            'text-decoration-color': [{'decoration': [colors]}],
            'text-transform': ['uppercase', 'lowercase', 'capitalize', 'normal-case'],
            'text-overflow': ['truncate', 'text-ellipsis', 'text-clip'],
            'text-wrap': [{'text': ['wrap', 'nowrap', 'balance', 'pretty']}],
            'indent': [{'indent': get_spacing_with_arbitrary()}],
            'vertical-align': [{
                'align': [
                    'baseline',
                    'top',
                    'middle',
                    'bottom',
                    'text-top',
                    'text-bottom',
                    'sub',
                    'super',
                    is_arbitrary_value,
                ],
            }],
            'whitespace': [{'whitespace': ['normal', 'nowrap', 'pre', 'pre-line', 'pre-wrap', 'break-spaces']}],
            'break': [{'break': ['normal', 'words', 'all', 'keep']}],
            'hyphens': [{'hyphens': ['none', 'manual', 'auto']}],
            'content': [{'content': ['none', is_arbitrary_value]}],

            # Backgrounds
            'bg-attachment': [{'bg': ['fixed', 'local', 'scroll']}],
            'bg-clip': [{'bg-clip': ['border', 'padding', 'content', 'text']}],
            'bg-opacity': [{'bg-opacity': [opacity]}],
            'bg-origin': [{'bg-origin': ['border', 'padding', 'content']}],
            'bg-position': [{'bg': [*get_positions(), is_arbitrary_position]}],
            'bg-repeat': [{'bg': ['no-repeat', {'repeat': ['', 'x', 'y', 'round', 'space']}]}],
            'bg-size': [{'bg': ['auto', 'cover', 'contain', is_arbitrary_size]}],
            'bg-image': [{
                'bg': [
                    'none',
                    {'gradient-to': ['t', 'tr', 'r', 'br', 'b', 'bl', 'l', 'tl']},
                    is_arbitrary_image,
                ],
            }],
            'bg-color': [{'bg': [colors]}],
            'gradient-from-pos': [{'from': [gradient_color_stop_positions]}],
            'gradient-via-pos': [{'via': [gradient_color_stop_positions]}],
            'gradient-to-pos': [{'to': [gradient_color_stop_positions]}],
            'gradient-from': [{'from': [gradient_color_stops]}],
            'gradient-via': [{'via': [gradient_color_stops]}],
            'gradient-to': [{'to': [gradient_color_stops]}],

            # Borders
            'rounded': [{'rounded': [border_radius]}],
            'rounded-s': [{'rounded-s': [border_radius]}],
            'rounded-e': [{'rounded-e': [border_radius]}],
            'rounded-t': [{'rounded-t': [border_radius]}],
            'rounded-r': [{'rounded-r': [border_radius]}],
            'rounded-b': [{'rounded-b': [border_radius]}],
            'rounded-l': [{'rounded-l': [border_radius]}],
            'rounded-ss': [{'rounded-ss': [border_radius]}],
            'rounded-se': [{'rounded-se': [border_radius]}],
            'rounded-ee': [{'rounded-ee': [border_radius]}],
            'rounded-es': [{'rounded-es': [border_radius]}],
            'rounded-tl': [{'rounded-tl': [border_radius]}],
            'rounded-tr': [{'rounded-tr': [border_radius]}],
            'rounded-br': [{'rounded-br': [border_radius]}],
            'rounded-bl': [{'rounded-bl': [border_radius]}],
            'border-w': [{'border': [border_width]}],
            'border-w-x': [{'border-x': [border_width]}],
            'border-w-y': [{'border-y': [border_width]}],
            'border-w-s': [{'border-s': [border_width]}],
            'border-w-e': [{'border-e': [border_width]}],
            'border-w-t': [{'border-t': [border_width]}],
            'border-w-r': [{'border-r': [border_width]}],
            'border-w-b': [{'border-b': [border_width]}],
            'border-w-l': [{'border-l': [border_width]}],
            'border-opacity': [{'border-opacity': [opacity]}],
            'border-style': [{'border': [*get_line_styles(), 'hidden']}],
            'divide-x': [{'divide-x': [border_width]}],
            'divide-x-reverse': ['divide-x-reverse'],
            'divide-y': [{'divide-y': [border_width]}],
            'divide-y-reverse': ['divide-y-reverse'],
            'divide-opacity': [{'divide-opacity': [opacity]}],
            'divide-style': [{'divide': get_line_styles()}],
            'border-color': [{'border': [border_color]}],
            'border-color-x': [{'border-x': [border_color]}],
            'border-color-y': [{'border-y': [border_color]}],
            'border-color-s': [{'border-s': [border_color]}],
            'border-color-e': [{'border-e': [border_color]}],
            'border-color-t': [{'border-t': [border_color]}],
            'border-color-r': [{'border-r': [border_color]}],
            'border-color-b': [{'border-b': [border_color]}],
            'border-color-l': [{'border-l': [border_color]}],
            'divide-color': [{'divide': [border_color]}],
            'outline-style': [{'outline': ['', *get_line_styles()]}],
            'outline-offset': [{'outline-offset': [is_length, is_arbitrary_value]}],
            'outline-w': [{'outline': [is_length, is_arbitrary_length]}],
            'outline-color': [{'outline': [colors]}],
            'ring-w': [{'ring': get_length_with_empty_and_arbitrary()}],
            'ring-w-inset': ['ring-inset'],
            'ring-color': [{'ring': [colors]}],
            'ring-opacity': [{'ring-opacity': [opacity]}],
            'ring-offset-w': [{'ring-offset': [is_length, is_arbitrary_length]}],
            'ring-offset-color': [{'ring-offset': [colors]}],

            # Effects
            'shadow': [{'shadow': ['', 'inner', 'none', is_tshirt_size, is_arbitrary_shadow]}],
            'shadow-color': [{'shadow': [is_any]}],
            'opacity': [{'opacity': [opacity]}],
            'mix-blend': [{'mix-blend': [*get_blend_modes(), 'plus-lighter', 'plus-darker']}],
            'bg-blend': [{'bg-blend': get_blend_modes()}],

            # Filters
            'filter': [{'filter': ['', 'none']}],
            'blur': [{'blur': [blur]}],
            'brightness': [{'brightness': [brightness]}],
            'contrast': [{'contrast': [contrast]}],
            'drop-shadow': [{'drop-shadow': ['', 'none', is_tshirt_size, is_arbitrary_value]}],
            'grayscale': [{'grayscale': [grayscale]}],
            'hue-rotate': [{'hue-rotate': [hue_rotate]}],
            'invert': [{'invert': [invert]}],
            'saturate': [{'saturate': [saturate]}],
            'sepia': [{'sepia': [sepia]}],
            'backdrop-filter': [{'backdrop-filter': ['', 'none']}],
            'backdrop-blur': [{'backdrop-blur': [blur]}],
            'backdrop-brightness': [{'backdrop-brightness': [brightness]}],
            'backdrop-contrast': [{'backdrop-contrast': [contrast]}],
            'backdrop-grayscale': [{'backdrop-grayscale': [grayscale]}],
            'backdrop-hue-rotate': [{'backdrop-hue-rotate': [hue_rotate]}],
            'backdrop-invert': [{'backdrop-invert': [invert]}],
            'backdrop-opacity': [{'backdrop-opacity': [opacity]}],
            'backdrop-saturate': [{'backdrop-saturate': [saturate]}],
            'backdrop-sepia': [{'backdrop-sepia': [sepia]}],

            # Tables
            'border-collapse': [{'border': ['collapse', 'separate']}],
            'border-spacing': [{'border-spacing': [border_spacing]}],
            'border-spacing-x': [{'border-spacing-x': [border_spacing]}],
            'border-spacing-y': [{'border-spacing-y': [border_spacing]}],
            'table-layout': [{'table': ['auto', 'fixed']}],
            'caption': [{'caption': ['top', 'bottom']}],

            # Transitions and Animation
            'transition': [{
                'transition': [
                    'none',
                    'all',
                    '',
                    'colors',
                    'opacity',
                    'shadow',
                    'transform',
                    is_arbitrary_value,
                ],
            }],
            'duration': [{'duration': get_number_and_arbitrary()}],
            'ease': [{'ease': ['linear', 'in', 'out', 'in-out', is_arbitrary_value]}],
            'delay': [{'delay': get_number_and_arbitrary()}],
            'animate': [{'animate': ['none', 'spin', 'ping', 'pulse', 'bounce', is_arbitrary_value]}],

            # Transforms
            'transform': [{'transform': ['', 'gpu', 'none']}],
            'scale': [{'scale': [scale]}],
            'scale-x': [{'scale-x': [scale]}],
            'scale-y': [{'scale-y': [scale]}],
            'rotate': [{'rotate': [is_integer, is_arbitrary_value]}],
            'translate-x': [{'translate-x': [translate]}],
            'translate-y': [{'translate-y': [translate]}],
            'skew-x': [{'skew-x': [skew]}],
            'skew-y': [{'skew-y': [skew]}],
            'transform-origin': [{
                'origin': [
                    'center',
                    'top',
                    'top-right',
                    'right',
                    'bottom-right',
                    'bottom',
                    'bottom-left',
                    'left',
                    'top-left',
                    is_arbitrary_value,
                ],
            }],

            # Interactivity
            'accent': [{'accent': ['auto', colors]}],
            'appearance': [{'appearance': ['none', 'auto']}],
            'cursor': [{
                'cursor': [
                    'auto',
                    'default',
                    'pointer',
                    'wait',
                    'text',
                    'move',
                    'help',
                    'not-allowed',
                    'none',
                    'context-menu',
                    'progress',
                    'cell',
                    'crosshair',
                    'vertical-text',
                    'alias',
                    'copy',
                    'no-drop',
                    'grab',
                    'grabbing',
                    'all-scroll',
                    'col-resize',
                    'row-resize',
                    'n-resize',
                    'e-resize',
                    's-resize',
                    'w-resize',
                    'ne-resize',
                    'nw-resize',
                    'se-resize',
                    'sw-resize',
                    'ew-resize',
                    'ns-resize',
                    'nesw-resize',
                    'nwse-resize',
                    'zoom-in',
                    'zoom-out',
                    is_arbitrary_value,
                ],
            }],
            'caret-color': [{'caret': [colors]}],
            'pointer-events': [{'pointer-events': ['none', 'auto']}],
            'resize': [{'resize': ['none', 'y', 'x', '']}],
            'scroll-behavior': [{'scroll': ['auto', 'smooth']}],
            'scroll-m': [{'scroll-m': get_spacing_with_arbitrary()}],
            'scroll-mx': [{'scroll-mx': get_spacing_with_arbitrary()}],
            'scroll-my': [{'scroll-my': get_spacing_with_arbitrary()}],
            'scroll-ms': [{'scroll-ms': get_spacing_with_arbitrary()}],
            'scroll-me': [{'scroll-me': get_spacing_with_arbitrary()}],
            'scroll-mt': [{'scroll-mt': get_spacing_with_arbitrary()}],
            'scroll-mr': [{'scroll-mr': get_spacing_with_arbitrary()}],
            'scroll-mb': [{'scroll-mb': get_spacing_with_arbitrary()}],
            'scroll-ml': [{'scroll-ml': get_spacing_with_arbitrary()}],
            'scroll-p': [{'scroll-p': get_spacing_with_arbitrary()}],
            'scroll-px': [{'scroll-px': get_spacing_with_arbitrary()}],
            'scroll-py': [{'scroll-py': get_spacing_with_arbitrary()}],
            'scroll-ps': [{'scroll-ps': get_spacing_with_arbitrary()}],
            'scroll-pe': [{'scroll-pe': get_spacing_with_arbitrary()}],
            'scroll-pt': [{'scroll-pt': get_spacing_with_arbitrary()}],
            'scroll-pr': [{'scroll-pr': get_spacing_with_arbitrary()}],
            'scroll-pb': [{'scroll-pb': get_spacing_with_arbitrary()}],
            'scroll-pl': [{'scroll-pl': get_spacing_with_arbitrary()}],
            'snap-align': [{'snap': ['start', 'end', 'center', 'align-none']}],
            'snap-stop': [{'snap': ['normal', 'always']}],
            'snap-type': [{'snap': ['none', 'x', 'y', 'both']}],
            'snap-strictness': [{'snap': ['mandatory', 'proximity']}],
            'touch': [{'touch': ['auto', 'none', 'manipulation']}],
            'touch-x': [{'touch-pan': ['x', 'left', 'right']}],
            'touch-y': [{'touch-pan': ['y', 'up', 'down']}],
            'touch-pz': ['touch-pinch-zoom'],
            'select': [{'select': ['none', 'text', 'all', 'auto']}],
            'will-change': [{'will-change': ['auto', 'scroll', 'contents', 'transform', is_arbitrary_value]}],

            # SVG
            'fill': [{'fill': [colors, 'none']}],
            'stroke-w': [{'stroke': [is_length, is_arbitrary_length, is_arbitrary_number]}],
            'stroke': [{'stroke': [colors, 'none']}],

            # Accessibility
            'sr': ['sr-only', 'not-sr-only'],
            'forced-color-adjust': [{'forced-color-adjust': ['auto', 'none']}],
        },
        'conflictingClassGroups': {
            'overflow': ['overflow-x', 'overflow-y'],
            'overscroll': ['overscroll-x', 'overscroll-y'],
            'inset': ['inset-x', 'inset-y', 'start', 'end', 'top', 'right', 'bottom', 'left'],
            'inset-x': ['right', 'left'],
            'inset-y': ['top', 'bottom'],
            'flex': ['basis', 'grow', 'shrink'],
            'gap': ['gap-x', 'gap-y'],
            'p': ['px', 'py', 'ps', 'pe', 'pt', 'pr', 'pb', 'pl'],
            'px': ['pr', 'pl'],
            'py': ['pt', 'pb'],
            'm': ['mx', 'my', 'ms', 'me', 'mt', 'mr', 'mb', 'ml'],
            'mx': ['mr', 'ml'],
            'my': ['mt', 'mb'],
            'size': ['w', 'h'],
            'font-size': ['leading'],
            'fvn-normal': [
                'fvn-ordinal',
                'fvn-slashed-zero',
                'fvn-figure',
                'fvn-spacing',
                'fvn-fraction',
            ],
            'fvn-ordinal': ['fvn-normal'],
            'fvn-slashed-zero': ['fvn-normal'],
            'fvn-figure': ['fvn-normal'],
            'fvn-spacing': ['fvn-normal'],
            'fvn-fraction': ['fvn-normal'],
            'line-clamp': ['display', 'overflow'],
            'rounded': [
                'rounded-s',
                'rounded-e',
                'rounded-t',
                'rounded-r',
                'rounded-b',
                'rounded-l',
                'rounded-ss',
                'rounded-se',
                'rounded-ee',
                'rounded-es',
                'rounded-tl',
                'rounded-tr',
                'rounded-br',
                'rounded-bl',
            ],
            'rounded-s': ['rounded-ss', 'rounded-es'],
            'rounded-e': ['rounded-se', 'rounded-ee'],
            'rounded-t': ['rounded-tl', 'rounded-tr'],
            'rounded-r': ['rounded-tr', 'rounded-br'],
            'rounded-b': ['rounded-br', 'rounded-bl'],
            'rounded-l': ['rounded-tl', 'rounded-bl'],
            'border-spacing': ['border-spacing-x', 'border-spacing-y'],
            'border-w': [
                'border-w-s',
                'border-w-e',
                'border-w-t',
                'border-w-r',
                'border-w-b',
                'border-w-l',
            ],
            'border-w-x': ['border-w-r', 'border-w-l'],
            'border-w-y': ['border-w-t', 'border-w-b'],
            'border-color': [
                'border-color-s',
                'border-color-e',
                'border-color-t',
                'border-color-r',
                'border-color-b',
                'border-color-l',
            ],
            'border-color-x': ['border-color-r', 'border-color-l'],
            'border-color-y': ['border-color-t', 'border-color-b'],
            'scroll-m': [
                'scroll-mx',
                'scroll-my',
                'scroll-ms',
                'scroll-me',
                'scroll-mt',
                'scroll-mr',
                'scroll-mb',
                'scroll-ml',
            ],
            'scroll-mx': ['scroll-mr', 'scroll-ml'],
            'scroll-my': ['scroll-mt', 'scroll-mb'],
            'scroll-p': [
                'scroll-px',
                'scroll-py',
                'scroll-ps',
                'scroll-pe',
                'scroll-pt',
                'scroll-pr',
                'scroll-pb',
                'scroll-pl',
            ],
            'scroll-px': ['scroll-pr', 'scroll-pl'],
            'scroll-py': ['scroll-pt', 'scroll-pb'],
            'touch': ['touch-x', 'touch-y', 'touch-pz'],
            'touch-x': ['touch'],
            'touch-y': ['touch'],
            'touch-pz': ['touch'],
        },
        'conflictingClassGroupModifiers': {
            'font-size': ['leading'],
        }
    }